---
# ansible-playbook mysql.yml
# Can be used for setting up MySQL server on Ubuntu 20.04

- name: Setup mysql
  hosts: "mysql"
  vars:
    mysql_root_password: 'snowball'
  tasks:
    - name: update system
      become: true
      apt:
        update_cache: true
        upgrade: 'yes'

    - name: ensure mysql is installed
      become: true
      apt:
        name: mysql-server
        state: present
        update_cache: true

    - name: Ensure mysql service is running
      service:
        name: mysql
        state: started
        enabled: True

    - name: Install python3-pymysql library
      become: true
      apt:
         name: python3-pymysql
         state: present

    - name: Set MySQL root password
      become: true
      community.mysql.mysql_user:
        login_host: 'localhost'
        login_user: 'root'
        login_password: ''
        name: 'root'
        password: '{{ mysql_root_password }}'
        state: present

    - name: MySQL create new user
      become: true
      mysql_user:
        login_host: 'localhost'
        login_user: 'root'
        login_password: ''
        name: 'snowball'
        password: 'testing'
        state: present