---
# ansible-playbook apt.yml

- name: run apt
  hosts: "*"
  tasks:
    - name: update system
      become: true
      apt:
        update_cache: true
        upgrade: 'yes'

    - name: install nginx
      become: true
      apt:
        name: nginx
        state: latest
        update_cache: true
    - name: start nginx
      become: true
      service:
        name: nginx
        state: started
    - name: copy the nginx config file and restart nginx
      become: yes
      copy:
        src: ./nginx_configs/static.cfg
        dest: /etc/nginx/sites-available/static
    - name: create symlink
      become: yes
      file:
        src: /etc/nginx/sites-available/static
        dest: /etc/nginx/sites-enabled/default
        state: link
    - name: restart nginx
      become: yes
      service:
        name: nginx
        state: restarted